version: "3.8"
services:

    # PHP Service
    php:
        build:
            context: .
            target: php
            args:
                - APP_ENV=${APP_ENV}
        environment:
            - APP_ENV=${APP_ENV}
            - CONTAINER_ROLE=app
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - 8100:8100
        depends_on:
            - database
            # - redis

    # Database Server
    database:
        image: postgres:14
        ports:
            -   5431:5432
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - db-data:/var/lib/postgresql/data

volumes:
    db-data: ~
